@startuml
start
:Start sensor monitorin;
:Read data from LDR;
:Read data from DHT11 (temperature, humidity);
:Store data in DynamoDB;
:Publish data in MQTT (AWS IoT);
if (Low light level?) then (yes)
  :Turn on servo to open blinds;
else (no)
  :Turn on servo to close blinds;
endif
if (Temperature > 20°C?) then (yes)
  :Turn on servo to open irrigation valve;
else (no)
  :Turn on servo to close irrigation valve;
endif
stop
@enduml